
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;



namespace Luban.Config
{
    public sealed partial class LocationText : Luban.BeanBase
    {
        public LocationText(ByteBuf _buf, string[] textList) 
        {
            Zh = ReadText(_buf, textList);
            En = _buf.ReadString();
        }

        public static LocationText DeserializeLocationText(ByteBuf _buf, string[] textList)
        {
            return new LocationText(_buf, textList);
        }

        public readonly string Zh;
        public readonly string En;

        public const int __ID__ = 106023586;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(Tables tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "zh:" + Zh + ","
            + "en:" + En + ","
            + "}";
        }
    }

}

